@startuml packages_FitFlow
set namespaceSeparator none
package "backend" as backend {
}
package "backend.alembic" as backend.alembic {
}
package "backend.alembic.env" as backend.alembic.env {
}
package "backend.app" as backend.app {
}
package "backend.app.api" as backend.app.api {
}
package "backend.app.api.v1" as backend.app.api.v1 {
}
package "backend.app.api.v1.api" as backend.app.api.v1.api {
}
package "backend.app.core" as backend.app.core {
}
package "backend.app.core.blacklist" as backend.app.core.blacklist {
}
package "backend.app.core.config" as backend.app.core.config {
}
package "backend.app.core.deps" as backend.app.core.deps {
}
package "backend.app.core.enums" as backend.app.core.enums {
}
package "backend.app.core.redis_client" as backend.app.core.redis_client {
}
package "backend.app.core.security" as backend.app.core.security {
}
package "backend.app.core.timezone" as backend.app.core.timezone {
}
package "backend.app.core.token_store" as backend.app.core.token_store {
}
package "backend.app.crud" as backend.app.crud {
}
package "backend.app.crud.base" as backend.app.crud.base {
}
package "backend.app.crud.crud_base_sync" as backend.app.crud.crud_base_sync {
}
package "backend.app.crud.crud_booking" as backend.app.crud.crud_booking {
}
package "backend.app.crud.crud_class_schedule" as backend.app.crud.crud_class_schedule {
}
package "backend.app.crud.crud_class_session" as backend.app.crud.crud_class_session {
}
package "backend.app.crud.crud_client" as backend.app.crud.crud_client {
}
package "backend.app.crud.crud_gym_class" as backend.app.crud.crud_gym_class {
}
package "backend.app.crud.crud_membership" as backend.app.crud.crud_membership {
}
package "backend.app.crud.crud_permission" as backend.app.crud.crud_permission {
}
package "backend.app.crud.crud_role" as backend.app.crud.crud_role {
}
package "backend.app.crud.crud_teacher" as backend.app.crud.crud_teacher {
}
package "backend.app.crud.crud_user" as backend.app.crud.crud_user {
}
package "backend.app.db" as backend.app.db {
}
package "backend.app.db.base" as backend.app.db.base {
}
package "backend.app.db.base_class" as backend.app.db.base_class {
}
package "backend.app.db.mixins" as backend.app.db.mixins {
}
package "backend.app.db.session" as backend.app.db.session {
}
package "backend.app.main" as backend.app.main {
}
package "backend.app.models" as backend.app.models {
}
package "backend.app.models.booking" as backend.app.models.booking {
}
package "backend.app.models.class_schedule" as backend.app.models.class_schedule {
}
package "backend.app.models.class_session" as backend.app.models.class_session {
}
package "backend.app.models.client" as backend.app.models.client {
}
package "backend.app.models.gym_class" as backend.app.models.gym_class {
}
package "backend.app.models.membership" as backend.app.models.membership {
}
package "backend.app.models.permission" as backend.app.models.permission {
}
package "backend.app.models.person" as backend.app.models.person {
}
package "backend.app.models.role" as backend.app.models.role {
}
package "backend.app.models.role_permissions" as backend.app.models.role_permissions {
}
package "backend.app.models.teacher" as backend.app.models.teacher {
}
package "backend.app.models.user" as backend.app.models.user {
}
package "backend.app.routers" as backend.app.routers {
}
package "backend.app.routers.auth" as backend.app.routers.auth {
}
package "backend.app.routers.bookings" as backend.app.routers.bookings {
}
package "backend.app.routers.class_schedules" as backend.app.routers.class_schedules {
}
package "backend.app.routers.class_sessions" as backend.app.routers.class_sessions {
}
package "backend.app.routers.clients" as backend.app.routers.clients {
}
package "backend.app.routers.front_desk" as backend.app.routers.front_desk {
}
package "backend.app.routers.gym_classes" as backend.app.routers.gym_classes {
}
package "backend.app.routers.memberships" as backend.app.routers.memberships {
}
package "backend.app.routers.teachers" as backend.app.routers.teachers {
}
package "backend.app.routers.users" as backend.app.routers.users {
}
package "backend.app.schemas" as backend.app.schemas {
}
package "backend.app.schemas.base" as backend.app.schemas.base {
}
package "backend.app.schemas.booking" as backend.app.schemas.booking {
}
package "backend.app.schemas.class_schedule" as backend.app.schemas.class_schedule {
}
package "backend.app.schemas.class_session" as backend.app.schemas.class_session {
}
package "backend.app.schemas.client" as backend.app.schemas.client {
}
package "backend.app.schemas.front_desk" as backend.app.schemas.front_desk {
}
package "backend.app.schemas.gym_class" as backend.app.schemas.gym_class {
}
package "backend.app.schemas.membership" as backend.app.schemas.membership {
}
package "backend.app.schemas.permission" as backend.app.schemas.permission {
}
package "backend.app.schemas.person" as backend.app.schemas.person {
}
package "backend.app.schemas.role" as backend.app.schemas.role {
}
package "backend.app.schemas.teacher" as backend.app.schemas.teacher {
}
package "backend.app.schemas.token" as backend.app.schemas.token {
}
package "backend.app.schemas.user" as backend.app.schemas.user {
}
package "backend.app.services" as backend.app.services {
}
package "backend.app.services.auth_service" as backend.app.services.auth_service {
}
package "backend.app.services.booking_service" as backend.app.services.booking_service {
}
package "backend.app.services.class_schedule_service" as backend.app.services.class_schedule_service {
}
package "backend.app.services.class_session_service" as backend.app.services.class_session_service {
}
package "backend.app.services.client_service" as backend.app.services.client_service {
}
package "backend.app.services.errors" as backend.app.services.errors {
}
package "backend.app.services.front_desk_service" as backend.app.services.front_desk_service {
}
package "backend.app.services.gym_class_service" as backend.app.services.gym_class_service {
}
package "backend.app.services.membership_service" as backend.app.services.membership_service {
}
package "backend.app.services.teacher_service" as backend.app.services.teacher_service {
}
package "backend.app.services.user_service" as backend.app.services.user_service {
}
backend.app.models.client --> backend.app.models.person
backend.app.services.class_session_service --> backend.app.core.enums
backend.app.services.class_session_service --> backend.app.schemas.class_session
backend.app.services.client_service --> backend.app.crud
backend.app.services.client_service --> backend.app.schemas.client
backend.app.models.teacher ..> backend.app.models.class_schedule
@enduml
