"""fix gym_class default_capacity

Revision ID: 6beb1fc321fd
Revises: d5f64f472402
Create Date: 2025-09-09 12:20:46.375630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6beb1fc321fd'
down_revision: Union[str, Sequence[str], None] = 'd5f64f472402'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gym_classes', 'default_capacity',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gym_classes', 'default_capacity',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
