"""Add ClassSchedule, ClassSession, Booking models and refactor GymClass/Teacher relationships

Revision ID: d5f64f472402
Revises: de9d327bfe41
Create Date: 2025-09-08 22:19:09.073474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd5f64f472402'
down_revision: Union[str, Sequence[str], None] = 'de9d327bfe41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gym_class_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('days_of_week', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('start_time', sa.Time(timezone=True), nullable=False),
    sa.Column('end_time', sa.Time(timezone=True), nullable=False),
    sa.Column('max_capacity', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['gym_class_id'], ['gym_classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('class_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('class_schedule_id', sa.UUID(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['class_schedule_id'], ['class_schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_schedule_id', 'start_datetime', name='_class_schedule_datetime_uc')
    )
    op.create_index(op.f('ix_class_sessions_start_datetime'), 'class_sessions', ['start_datetime'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('class_session_id', sa.UUID(), nullable=False),
    sa.Column('booking_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('Confirmado', 'Cancelado', 'Pendiente', name='bookingstatus'), nullable=False),
    sa.ForeignKeyConstraint(['class_session_id'], ['class_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('gym_classes', sa.Column('default_capacity', sa.Integer(), nullable=True))
    op.drop_column('gym_classes', 'schedule')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gym_classes', sa.Column('schedule', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('gym_classes', 'default_capacity')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_class_sessions_start_datetime'), table_name='class_sessions')
    op.drop_table('class_sessions')
    op.drop_table('class_schedules')
    # ### end Alembic commands ###
